#!/bin/bash

YELLOW="\033[1;33m"
CYAN="\033[0;36m"
RED="\033[0;31m"
NC="\033[0m"

#iw dev | awk '{if($1=="Interface") {print $2; exit}}'

NM_STATUS=$( systemctl status network-manager.service | grep -o "dead" )
PARENT_DIR="$(dirname "$(readlink -f "$0")")"
WIFI_DEV=$( ip -br link | awk '/<BROADCAST,MULTICAST,UP/ {print $1; exit}' )
SELENIUM_FIREFOX=$( find ~/.mozilla/firefox -type d -name "*.Selenium" )
SELENIUM_F_BIN=$( which firefox )

if pgrep xterm &> /dev/null ; then
	sudo killall xterm 
fi

if [ -z "$SELENIUM_F_BIN" ] ; then
	echo -e "[${RED}!${NC}] Err: No Firefox Installation Found [${RED}!${NC}]\n"
	sleep 7
	exit
fi

#Check if Firefox Profile Exists, else Create Profile Selenium
if [ -z "$SELENIUM_FIREFOX" ] ; then
	firefox -no-remote -CreateProfile Selenium >/dev/null 2>&1
	firefox -no-remote -headless -P Selenium >/dev/null 2>&1 &
	THIS_PID="$!"
	SELENIUM_FIREFOX=$( find ~/.mozilla/firefox -type d -name "*.Selenium" )
	#Wait to Populate Profile
	while [ ! -f "$SELENIUM_FIREFOX/addons.json" ] ; do
		sleep 1
	done
	kill -9 "$THIS_PID"
	if [ -f "$PARENT_DIR/firecache/prefs.js" ] ; then 
		cp -f "$PARENT_DIR/firecache/prefs.js" "$SELENIUM_FIREFOX/prefs.js"
	fi
fi

#Dont Query For DNS Check 1
if [ -f "/etc/network/interfaces" ] ; then 
	if [ -z "$( grep -R 'dns-nameservers' /etc/network/interfaces )" ] ; then 
		echo "dns-nameservers 75.75.75.75 75.75.76.76" >> /etc/network/interface
	fi
fi

#Dont Query For DNS Check 2
DHCLIENT_FILE=$(find /etc -regex '.*dhcp[0-9]*/dhclient.conf')
if [ -f "$DHCLIENT_FILE" ] ; then
	STRING_OF_INTEREST="supersede domain-name-servers 75.75.75.75, 75.75.76.76;"
	SEARCH_RESULT=$(echo -n $(grep -R "$STRING_OF_INTEREST" $DHCLIENT_FILE) )
	if [[ -z "$SEARCH_RESULT"  ]] ; then
		echo "$STRING_OF_INTEREST" >> $DHCLIENT_FILE
	fi
fi  


#Include Staple as Path Variable
if [ -z "$(which staple)" ] ; then
	ln -s "$PARENT_DIR/staple" "${PATH%%:*}/staple"
fi

#Ensure Network Manager is Not Dead on Start
if [ -n  "$NM_STATUS" ]; then 
	echo -e "\nMake Sure Network Manager is Enabled Before Running [${CYAN}staple${NC}] Script\n"
	rm -f "/etc/resolv.conf"
	systemctl restart network-manager.service
	while [ ! -f "/etc/resolv.conf" ] ; do 
		echo -e "\tWaiting For New [${CYAN}resolv.conf${NC}] Script\n"
		sleep 2
	done
	clear
fi

#Check That DIG_DNS can resolve
DIG_DNS=$( dig +time=3 +tries=1 +noedns +noall +answer +short \
		  xfwweb.g.comcast.net @75.75.75.75 )

while [[ ! $DIG_DNS =~ ([0-9]{1,3}\.)+([0-9]{1,3}) ]] ; do
	DIG_DNS=$(dig +time=1 +tries=1 +noedns +noall +answer +short xfwweb.g.comcast.net @75.75.75.75)
	sleep 0.75
done


#Execute in Target Folder, Not Current Open Directory
cd $PARENT_DIR
sudo xterm -T "Xfinity Wifi" -geometry 70x20+0+0 -fa monospace -fs 8 \
		-e "$PARENT_DIR/script1.sh $SELENIUM_FIREFOX $SELENIUM_F_BIN" & disown
